spring:
  application:
    name: extended-mysql-kotlin-skeleton

  cloud:
    config:
      uri: http://config-user:${CONFIG_SERVER_PASSWORD:dev}@${CONFIG_SERVER_HOST:localhost}:8888
      failFast: true
